import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Box,
  TextField,
  Typography,
  IconButton,
  Tooltip,
  Collapse,
  Grid,
  Chip,
  Alert,
  Button,
  CircularProgress,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Autocomplete,
  ToggleButtonGroup,
  ToggleButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Divider,
  Stack,
} from "@mui/material";
import type { SelectChangeEvent } from "@mui/material";
import {
  ChevronDown,
  ChevronUp,
  Monitor,
  Smartphone,
  Send,
  Eye,
  User,
  Bot,
  Search,
  Settings2,
  Mail,
} from "lucide-react";
import { useRequestContext } from "@providers/request-provider";
import { useNotificationsService } from "@hooks";
import { useErrorDetailsModal } from "@providers/error-details-modal-provider";
import { useUserInfo } from "@providers/user-provider";
import {
  ContactDetailsDto,
  EmailTemplatePreviewRequestDto,
  EmailTemplatePreviewResultDto,
  EmailTemplateSendTestDto,
} from "@lib/network/swagger-client";
import { showApiError } from "@utils/api-error-parser";

type ContactType = "Full" | "Standard" | "Basic" | "Minimal";

type PreviewDataMode = "dummy" | "contact";

export interface TemplatePreviewProps {
  /** Raw template source (HTML) */
  source: string;
  /** Template subject line */
  subject?: string;
  /** From email */
  fromEmail?: string;
  /** From name */
  fromName?: string;
  /** Template language */
  language?: string;
  /** Height for the preview container */
  height?: string;
}

interface CustomParam {
  key: string;
  value: string;
  autoGenerated?: boolean;
}

/**
 * Normalise legacy backend template tokens to Liquid syntax.
 */
export function normalizePlaceholders(source: string): string {
  let result = source;
  result = result.replace(/<%\s*(\w+)\s*%>/g, (_, k) => `{{ ${k} }}`);
  result = result.replace(/&lt;%\s*(\w+)\s*%&gt;/g, (_, k) => `{{ ${k} }}`);
  result = result.replace(/\$\{\s*(\w+)\s*\}/g, (_, k) => `{{ ${k} }}`);
  return result;
}

const CONTACT_TYPE_OPTIONS: {
  value: ContactType;
  label: string;
  description: string;
}[] = [
  { value: "Full", label: "Full", description: "All fields" },
  { value: "Standard", label: "Standard", description: "Common fields" },
  { value: "Basic", label: "Basic", description: "Minimal fields" },
  { value: "Minimal", label: "Minimal", description: "Essential only" },
];

/**
 * Parameters the backend resolves from the contact record.
 * Any template token NOT in this set is considered a custom parameter.
 */
const SERVER_KNOWN_PARAMS = new Set([
  "Email",
  "FirstName",
  "LastName",
  "FullName",
  "MiddleName",
  "Prefix",
  "Phone",
  "JobTitle",
  "CompanyName",
  "Department",
  "CityName",
  "State",
  "Zip",
  "Address1",
  "Address2",
  "Language",
  "CountryCode",
  "ContinentCode",
  "AccountName",
  "AccountSiteUrl",
  "DomainName",
]);

/** Case-insensitive lookup for server-known params. */
const SERVER_KNOWN_LOWER = new Set([...SERVER_KNOWN_PARAMS].map((p) => p.toLowerCase()));

/**
 * Extract simple (non-nested) Liquid-style tokens from template source.
 * Skips tokens containing dots (e.g. `account.name`) and Liquid
 * control tags like `if`, `endif`, `for`, `endfor`, `else`, etc.
 */
function extractTemplateTokens(template: string): string[] {
  const seen = new Set<string>();
  const results: string[] = [];
  const controlKeywords = new Set([
    "if",
    "else",
    "elsif",
    "endif",
    "unless",
    "endunless",
    "for",
    "endfor",
    "case",
    "endcase",
    "when",
    "capture",
    "endcapture",
    "comment",
    "endcomment",
    "raw",
    "endraw",
    "assign",
    "increment",
    "decrement",
    "include",
    "render",
    "break",
    "continue",
    "cycle",
    "tablerow",
    "endtablerow",
  ]);

  // Match {{ token }} and also {%- / {%
  const re = /\{\{[\-]?\s*([\w.]+)\s*[\-]?\}\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(template)) !== null) {
    const token = m[1];
    // Skip nested (dotted) tokens
    if (token.includes(".")) continue;
    // Skip Liquid control keywords
    if (controlKeywords.has(token.toLowerCase())) continue;
    const key = token;
    if (!seen.has(key.toLowerCase())) {
      seen.add(key.toLowerCase());
      results.push(key);
    }
  }
  return results;
}

/**
 * Best-guess a sample value for a custom template parameter
 * based on its name.
 */
function guessParamValue(name: string): string {
  const lower = name.toLowerCase();

  if (lower.includes("email")) return "customer@example.com";
  if (lower.includes("name") && lower.includes("customer")) return "Alex Johnson";
  if (lower.includes("name")) return "Sample Name";
  if (lower.includes("phone") || lower.includes("tel")) return "+1-555-0100";
  if (lower.includes("date")) return "2026-01-15";
  if (lower.includes("url") || lower.includes("link")) return "https://example.com";
  if (lower.includes("amount") || lower.includes("total")) return "99.00";
  if (lower.includes("price") || lower.includes("fee")) return "19.99";
  if (lower.includes("currency")) return "USD";
  if (lower.includes("quantity") || lower.includes("qty")) return "1";
  if (lower.includes("id") || lower.includes("number")) return "12345";
  if (lower.includes("ref")) return "REF-001";
  if (lower.includes("code") || lower.includes("key")) return "XXXX-XXXX-XXXX";
  if (lower.includes("product")) return "Sample Product";
  if (lower.includes("source") || lower.includes("platform")) return "Web";
  if (lower.includes("order")) return "ORD-001";
  if (lower.includes("status")) return "Active";
  if (lower.includes("company") || lower.includes("org")) return "Acme Inc.";
  if (lower.includes("address")) return "123 Main Street";
  if (lower.includes("city")) return "New York";
  if (lower.includes("state")) return "NY";
  if (lower.includes("zip") || lower.includes("postal")) return "10001";
  if (lower.includes("country")) return "US";
  if (lower.includes("title")) return "Sample Title";
  if (lower.includes("description") || lower.includes("desc")) return "Sample description text";
  if (lower.includes("message") || lower.includes("note")) return "Sample message";
  if (lower.includes("license")) return "LIC-XXXX-XXXX";

  return `Sample ${name}`;
}

const CUSTOM_PARAMS_STORAGE_KEY = "email-tpl-preview-custom-params";
const DATA_MODE_STORAGE_KEY = "email-tpl-preview-data-mode";
const CONTACT_TYPE_STORAGE_KEY = "email-tpl-preview-contact-type";
const SELECTED_CONTACT_STORAGE_KEY = "email-tpl-preview-selected-contact";

function loadStoredCustomParams(): CustomParam[] {
  try {
    const raw = localStorage.getItem(CUSTOM_PARAMS_STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveStoredCustomParams(params: CustomParam[]) {
  try {
    localStorage.setItem(CUSTOM_PARAMS_STORAGE_KEY, JSON.stringify(params));
  } catch {
    /* quota exceeded */
  }
}

function loadStoredDataMode(): PreviewDataMode {
  try {
    const v = localStorage.getItem(DATA_MODE_STORAGE_KEY);
    return v === "contact" ? "contact" : "dummy";
  } catch {
    return "dummy";
  }
}

function loadStoredContactType(): ContactType {
  try {
    const v = localStorage.getItem(CONTACT_TYPE_STORAGE_KEY);
    if (v === "Full" || v === "Standard" || v === "Basic" || v === "Minimal") return v;
    return "Full";
  } catch {
    return "Full";
  }
}

function loadStoredSelectedContact(): ContactDetailsDto | null {
  try {
    const raw = localStorage.getItem(SELECTED_CONTACT_STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

/* ------------------------------------------------------------------ */
/*  Reusable "email header row" used in both preview & envelope       */
/* ------------------------------------------------------------------ */
const HeaderRow: React.FC<{
  label: string;
  children: React.ReactNode;
}> = ({ label, children }) => (
  <Box
    sx={{
      display: "flex",
      gap: 1,
      alignItems: "baseline",
      py: 0.5,
    }}
  >
    <Typography
      variant="body2"
      color="text.secondary"
      sx={{
        width: 60,
        minWidth: 60,
        textAlign: "left",
        flexShrink: 0,
      }}
    >
      {label}
    </Typography>
    <Typography variant="body1" sx={{ wordBreak: "break-word", minWidth: 0 }}>
      {children}
    </Typography>
  </Box>
);

/* ================================================================== */
/*  Main component                                                    */
/* ================================================================== */
export const TemplatePreview: React.FC<TemplatePreviewProps> = ({
  source,
  subject,
  fromEmail,
  fromName,
  language,
  height = "calc(100vh - 300px)",
}) => {
  const { client } = useRequestContext();
  const { notificationsService } = useNotificationsService();
  const { Show: showErrorModal } = useErrorDetailsModal();
  const userInfo = useUserInfo();

  // Preview state
  const [previewHtml, setPreviewHtml] = useState("");
  const [previewSubject, setPreviewSubject] = useState("");
  const [previewContact, setPreviewContact] = useState<{
    name?: string;
    email?: string;
  } | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);

  // UI state
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [mobilePreview, setMobilePreview] = useState(false);

  // Data mode
  const [dataMode, setDataMode] = useState<PreviewDataMode>(loadStoredDataMode);
  const [contactType, setContactType] = useState<ContactType>(loadStoredContactType);

  // Contact search
  const [contactSearchQuery, setContactSearchQuery] = useState("");
  const [contactOptions, setContactOptions] = useState<ContactDetailsDto[]>([]);
  const [selectedContact, setSelectedContact] = useState<ContactDetailsDto | null>(
    loadStoredSelectedContact
  );
  const [contactLoading, setContactLoading] = useState(false);
  const contactSearchTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const toggleGroupRef = useRef<HTMLDivElement>(null);
  const [toggleGroupWidth, setToggleGroupWidth] = useState<number>(0);

  useEffect(() => {
    const el = toggleGroupRef.current;
    if (!el) return;
    const observer = new ResizeObserver(() => {
      setToggleGroupWidth(el.offsetWidth);
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, [settingsOpen]);

  // Persist data mode, contact type, and selected contact
  useEffect(() => {
    localStorage.setItem(DATA_MODE_STORAGE_KEY, dataMode);
  }, [dataMode]);

  useEffect(() => {
    localStorage.setItem(CONTACT_TYPE_STORAGE_KEY, contactType);
  }, [contactType]);

  useEffect(() => {
    try {
      if (selectedContact) {
        localStorage.setItem(SELECTED_CONTACT_STORAGE_KEY, JSON.stringify(selectedContact));
      } else {
        localStorage.removeItem(SELECTED_CONTACT_STORAGE_KEY);
      }
    } catch {
      /* quota exceeded */
    }
  }, [selectedContact]);

  // Custom parameters
  const [customParams, setCustomParams] = useState<CustomParam[]>(() => loadStoredCustomParams());
  const [paramsExpanded, setParamsExpanded] = useState(false);

  /**
   * Tokens detected in the current template that are NOT
   * server-known (i.e. custom parameters the user must supply).
   */
  const templateCustomTokens = useMemo(() => {
    if (!source.trim()) return [] as string[];
    const tokens = extractTemplateTokens(source);
    return tokens.filter((t) => !SERVER_KNOWN_LOWER.has(t.toLowerCase()));
  }, [source]);

  /* ------ auto-detect custom template tokens ------ */
  useEffect(() => {
    if (templateCustomTokens.length === 0) return;

    setCustomParams((prev) => {
      const existingKeys = new Set(prev.map((p) => p.key.toLowerCase()));
      const newParams: CustomParam[] = [];
      for (const token of templateCustomTokens) {
        if (!existingKeys.has(token.toLowerCase())) {
          newParams.push({
            key: token,
            value: guessParamValue(token),
            autoGenerated: true,
          });
        }
      }
      if (newParams.length === 0) return prev;
      const merged = [...prev, ...newParams];
      if (newParams.length > 0) setParamsExpanded(true);
      return merged;
    });
  }, [templateCustomTokens]);

  /**
   * Only show custom params whose keys match a token found in
   * the current template source (case-insensitive).
   */
  const visibleCustomParams = useMemo(() => {
    if (templateCustomTokens.length === 0) return [];
    const tokenSet = new Set(templateCustomTokens.map((t) => t.toLowerCase()));
    return customParams.filter((p) => tokenSet.has(p.key.trim().toLowerCase()));
  }, [customParams, templateCustomTokens]);

  // Send test dialog
  const [sendTestOpen, setSendTestOpen] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState(() => userInfo?.details?.email || "");
  const [isSending, setIsSending] = useState(false);

  /* ------ contact debounced search ------ */
  useEffect(() => {
    if (dataMode !== "contact") return;
    if (contactSearchQuery.length < 2) {
      setContactOptions([]);
      return;
    }
    if (contactSearchTimerRef.current) {
      clearTimeout(contactSearchTimerRef.current);
    }
    contactSearchTimerRef.current = setTimeout(async () => {
      setContactLoading(true);
      try {
        const resp = await client.api.contactsList({
          query: contactSearchQuery,
        });
        setContactOptions(resp.data || []);
      } catch {
        setContactOptions([]);
      } finally {
        setContactLoading(false);
      }
    }, 400);
    return () => {
      if (contactSearchTimerRef.current) {
        clearTimeout(contactSearchTimerRef.current);
      }
    };
  }, [contactSearchQuery, dataMode, client]);

  /* ------ custom params map (only tokens present in template) ------ */
  const customTemplateParameters = useMemo(() => {
    const map: Record<string, string> = {};
    for (const p of visibleCustomParams) {
      if (p.key.trim()) map[p.key.trim()] = p.value;
    }
    return Object.keys(map).length > 0 ? map : undefined;
  }, [visibleCustomParams]);

  /* ------ preview API ------ */
  const fetchPreview = useCallback(async () => {
    if (!source.trim()) {
      setPreviewError("Template body is empty.");
      return;
    }
    if (!subject?.trim() || !fromEmail?.trim() || !fromName?.trim()) {
      setPreviewError("Subject, sender email and sender name are required to preview.");
      return;
    }

    setIsLoading(true);
    setPreviewError(null);

    try {
      const request: EmailTemplatePreviewRequestDto = {
        subject,
        bodyTemplate: source,
        fromEmail,
        fromName,
        language: language || undefined,
        customTemplateParameters,
      };

      if (dataMode === "dummy") {
        request.contactType = contactType;
        request.contactId = null;
      } else if (dataMode === "contact" && selectedContact?.id) {
        request.contactId = selectedContact.id;
        request.contactType = null;
      } else if (dataMode === "contact") {
        setPreviewError("Please select a contact first.");
        setIsLoading(false);
        return;
      }

      const resp = await client.api.emailTemplatesPreviewCreate(request);
      const result: EmailTemplatePreviewResultDto = resp.data;
      setPreviewHtml(result.renderedBody || "");
      setPreviewSubject(result.renderedSubject || "");
      if (result.previewContactName || result.previewContactEmail) {
        setPreviewContact({
          name: result.previewContactName,
          email: result.previewContactEmail,
        });
      } else {
        setPreviewContact(null);
      }
    } catch (error) {
      showApiError(error, notificationsService, showErrorModal, "Preview failed");
      setPreviewError("Failed to generate preview.");
    } finally {
      setIsLoading(false);
    }
  }, [
    source,
    subject,
    fromEmail,
    fromName,
    language,
    dataMode,
    contactType,
    selectedContact,
    customTemplateParameters,
    client,
    notificationsService,
    showErrorModal,
  ]);

  /* auto-fetch on mount and whenever preview inputs change */
  const refreshTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const prevParamsRef = useRef(customTemplateParameters);

  useEffect(() => {
    if (!source.trim() || !subject?.trim() || !fromEmail?.trim() || !fromName?.trim()) {
      return;
    }

    const paramsChanged = prevParamsRef.current !== customTemplateParameters;
    prevParamsRef.current = customTemplateParameters;

    if (refreshTimerRef.current) {
      clearTimeout(refreshTimerRef.current);
    }

    if (paramsChanged) {
      // Debounce when the change came from typing parameter values
      refreshTimerRef.current = setTimeout(() => {
        fetchPreview();
      }, 600);
    } else {
      // Immediate for discrete selections (dataMode, contactType, selectedContact)
      fetchPreview();
    }

    return () => {
      if (refreshTimerRef.current) {
        clearTimeout(refreshTimerRef.current);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dataMode, contactType, selectedContact, customTemplateParameters]);

  /* ------ send test ------ */
  const handleSendTest = useCallback(async () => {
    if (!recipientEmail.trim()) {
      notificationsService.error("Please enter a recipient email.");
      return;
    }
    if (!source.trim()) {
      notificationsService.error("Template body is empty.");
      return;
    }
    if (!subject?.trim()) {
      notificationsService.error("Template subject is required.");
      return;
    }
    if (!fromEmail?.trim()) {
      notificationsService.error("Sender email is required.");
      return;
    }
    if (!fromName?.trim()) {
      notificationsService.error("Sender name is required.");
      return;
    }

    setIsSending(true);
    try {
      const request: EmailTemplateSendTestDto = {
        subject,
        bodyTemplate: source,
        fromEmail,
        fromName,
        recipientEmail: recipientEmail.trim(),
        customTemplateParameters,
      };

      if (dataMode === "dummy") {
        request.contactType = contactType;
        request.contactId = null;
      } else if (dataMode === "contact") {
        request.contactId = selectedContact?.id ?? null;
        request.contactType = null;
      }

      await client.api.emailTemplatesSendTestCreate(request);
      notificationsService.success(`Test email sent to ${recipientEmail.trim()}`);
      setSendTestOpen(false);
    } catch (error) {
      showApiError(error, notificationsService, showErrorModal, "Failed to send test email");
    } finally {
      setIsSending(false);
    }
  }, [
    recipientEmail,
    source,
    subject,
    fromEmail,
    fromName,
    dataMode,
    contactType,
    selectedContact,
    customTemplateParameters,
    client,
    notificationsService,
    showErrorModal,
  ]);

  /* ------ custom params helpers ------ */
  useEffect(() => {
    saveStoredCustomParams(customParams);
  }, [customParams]);

  const updateCustomParam = (idx: number, updates: Partial<CustomParam>) => {
    setCustomParams((prev) => {
      const next = [...prev];
      next[idx] = { ...next[idx], ...updates };
      return next;
    });
  };

  const getContactLabel = (c: ContactDetailsDto) => {
    const parts: string[] = [];
    if (c.firstName) parts.push(c.firstName);
    if (c.lastName) parts.push(c.lastName);
    const name = parts.join(" ") || "Unnamed";
    return c.email ? `${name} (${c.email})` : name;
  };

  /* ================================================================ */
  /*  RENDER                                                          */
  /* ================================================================ */
  const canPreview =
    !!source.trim() && !!subject?.trim() && !!fromEmail?.trim() && !!fromName?.trim();

  return (
    <Box sx={{ display: "flex", flexDirection: "column", height }}>
      {/* ---- Top action bar ---- */}
      <Stack
        direction="row"
        alignItems="center"
        spacing={0.5}
        sx={{
          px: 1.5,
          py: 0.75,
          borderBottom: "1px solid",
          borderColor: "divider",
          bgcolor: "background.paper",
        }}
      >
        <Tooltip title="Preview settings">
          <IconButton
            size="small"
            onClick={() => setSettingsOpen((o) => !o)}
            color={settingsOpen ? "primary" : "default"}
            sx={{ width: 32, height: 32 }}
          >
            <Settings2 size={18} />
          </IconButton>
        </Tooltip>

        <Divider orientation="vertical" flexItem sx={{ mx: 0.5 }} />

        <ToggleButtonGroup
          size="small"
          exclusive
          value={mobilePreview ? "mobile" : "desktop"}
          onChange={(_, v) => {
            if (v) setMobilePreview(v === "mobile");
          }}
          sx={{
            height: 32,
            "& .MuiToggleButton-root": { px: 1 },
          }}
        >
          <ToggleButton value="desktop">
            <Monitor size={17} />
          </ToggleButton>
          <ToggleButton value="mobile">
            <Smartphone size={17} />
          </ToggleButton>
        </ToggleButtonGroup>

        <Chip
          label="HTML"
          size="small"
          variant="outlined"
          color="default"
          sx={{ ml: 0.5, height: 28 }}
        />

        {isLoading && <CircularProgress size={18} sx={{ ml: 1 }} />}

        <Box sx={{ flex: 1 }} />

        <Button
          size="small"
          variant="outlined"
          startIcon={<Send size={14} />}
          onClick={() => setSendTestOpen(true)}
          sx={{ textTransform: "none" }}
        >
          Send Test
        </Button>
      </Stack>

      {/* ---- Settings drawer ---- */}
      <Collapse in={settingsOpen}>
        <Box
          sx={{
            px: 2,
            py: 1.5,
            borderBottom: "1px solid",
            borderColor: "divider",
            bgcolor: "grey.50",
          }}
        >
          {/* Data Source row */}
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: "80px auto 1fr auto",
              columnGap: 2,
              alignItems: "center",
              mb: 1.5,
            }}
          >
            <Typography variant="caption" color="text.secondary">
              Data source
            </Typography>
            <ToggleButtonGroup
              ref={toggleGroupRef}
              size="small"
              value={dataMode}
              exclusive
              onChange={(_, v) => {
                if (v) setDataMode(v);
              }}
              sx={{
                height: 40,
                "& .MuiToggleButton-root": {
                  px: 1.5,
                },
              }}
            >
              <ToggleButton value="dummy">
                <Bot size={14} />
                <Typography variant="caption" sx={{ ml: 0.5 }}>
                  Dummy
                </Typography>
              </ToggleButton>
              <ToggleButton value="contact">
                <Search size={14} />
                <Typography variant="caption" sx={{ ml: 0.5 }}>
                  Contact
                </Typography>
              </ToggleButton>
            </ToggleButtonGroup>

            {/* Inline contact type or search */}
            <Box>
              {dataMode === "dummy" && (
                <FormControl size="small" sx={{ minWidth: 150 }}>
                  <InputLabel>Type</InputLabel>
                  <Select
                    value={contactType}
                    label="Type"
                    onChange={(e: SelectChangeEvent) =>
                      setContactType(e.target.value as ContactType)
                    }
                  >
                    {CONTACT_TYPE_OPTIONS.map((o) => (
                      <MenuItem key={o.value} value={o.value}>
                        {o.label}{" "}
                        <Typography
                          component="span"
                          variant="caption"
                          color="text.secondary"
                          sx={{ ml: 0.5 }}
                        >
                          — {o.description}
                        </Typography>
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              )}

              {dataMode === "contact" && (
                <Autocomplete
                  size="small"
                  options={contactOptions}
                  getOptionLabel={getContactLabel}
                  value={selectedContact}
                  loading={contactLoading}
                  onInputChange={(_, v) => setContactSearchQuery(v)}
                  onChange={(_, v) => setSelectedContact(v)}
                  isOptionEqualToValue={(a, b) => a.id === b.id}
                  noOptionsText={
                    contactSearchQuery.length < 2
                      ? "Type at least 2 characters"
                      : "No contacts found"
                  }
                  renderOption={(props, option) => (
                    <li {...props} key={option.id}>
                      <Box>
                        <Typography variant="body2">
                          {option.firstName} {option.lastName}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {option.email}
                        </Typography>
                      </Box>
                    </li>
                  )}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Search contact"
                      placeholder="Name or email"
                      slotProps={{
                        input: {
                          ...params.InputProps,
                          endAdornment: (
                            <>
                              {contactLoading ? (
                                <CircularProgress color="inherit" size={16} />
                              ) : null}
                              {params.InputProps.endAdornment}
                            </>
                          ),
                        },
                      }}
                    />
                  )}
                  sx={{ minWidth: 260 }}
                />
              )}
            </Box>

            {/* Custom parameters toggle */}
            <Box sx={{ justifySelf: "end" }}>
              {visibleCustomParams.length > 0 && (
                <Button
                  size="small"
                  variant="text"
                  onClick={() => setParamsExpanded((p) => !p)}
                  endIcon={paramsExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  sx={{
                    textTransform: "none",
                    px: 1,
                    color: "text.secondary",
                  }}
                >
                  {visibleCustomParams.length} custom{" "}
                  {visibleCustomParams.length === 1 ? "parameter" : "parameters"}
                </Button>
              )}
            </Box>
          </Box>

          <Collapse in={paramsExpanded && visibleCustomParams.length > 0}>
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: `80px ${toggleGroupWidth > 0 ? toggleGroupWidth : 160}px 1fr`,
                columnGap: 2,
                rowGap: 0.75,
                maxHeight: 240,
                overflowY: "auto",
                alignItems: "center",
              }}
            >
              {visibleCustomParams.map((param) => {
                const idx = customParams.indexOf(param);
                return (
                  <React.Fragment key={param.key}>
                    <Box />
                    <TextField size="small" value={param.key} disabled />
                    <TextField
                      size="small"
                      placeholder="Value"
                      value={param.value}
                      onChange={(e) =>
                        updateCustomParam(idx, {
                          value: e.target.value,
                        })
                      }
                    />
                  </React.Fragment>
                );
              })}
            </Box>
          </Collapse>
        </Box>
      </Collapse>

      {/* ---- Error ---- */}
      {previewError && (
        <Alert severity="warning" sx={{ borderRadius: 0 }}>
          {previewError}
        </Alert>
      )}

      {/* ---- Loading ---- */}
      {isLoading && (
        <Box
          sx={{
            flex: 1,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            bgcolor: "grey.50",
          }}
        >
          <Stack alignItems="center" spacing={1}>
            <CircularProgress size={28} />
            <Typography variant="caption" color="text.secondary">
              Rendering preview...
            </Typography>
          </Stack>
        </Box>
      )}

      {/* ---- Preview area (envelope + iframe) ---- */}
      {!isLoading && (
        <Box
          sx={{
            flex: 1,
            display: "flex",
            justifyContent: "center",
            bgcolor: mobilePreview ? "grey.100" : "white",
            overflow: "hidden",
            p: mobilePreview ? 3 : 0,
            transition: "background-color 0.3s ease",
          }}
        >
          {previewHtml ? (
            <Box
              sx={{
                width: mobilePreview ? "375px" : "100%",
                height: "100%",
                display: "flex",
                flexDirection: "column",
                transition: "width 0.3s ease",
                background: "white",
              }}
            >
              {/* Envelope header */}
              {(previewSubject || previewContact || fromEmail) && (
                <Box
                  sx={{
                    px: "5px",
                    py: 1.5,
                    borderBottom: "1px solid",
                    borderColor: "divider",
                    bgcolor: "background.paper",
                  }}
                >
                  {fromName && fromEmail && (
                    <HeaderRow label="From:">
                      {fromName} &lt;{fromEmail}&gt;
                    </HeaderRow>
                  )}
                  {previewContact && (
                    <HeaderRow label="To:">
                      {previewContact.name || "Contact"}{" "}
                      {previewContact.email && <>&lt;{previewContact.email}&gt;</>}
                    </HeaderRow>
                  )}
                  {previewSubject && <HeaderRow label="Subject:">{previewSubject}</HeaderRow>}
                </Box>
              )}
              {/* Email body */}
              <iframe
                srcDoc={`<div style="padding:5px 5px">${previewHtml}</div>`}
                title="Email Preview"
                sandbox="allow-same-origin allow-scripts"
                style={{
                  border: "none",
                  width: "100%",
                  flex: 1,
                  background: "white",
                }}
              />
            </Box>
          ) : (
            !previewError && (
              <Stack
                alignItems="center"
                justifyContent="center"
                spacing={1}
                sx={{ flex: 1, py: 6 }}
              >
                <Mail size={32} color="#bbb" />
                <Typography variant="body2" color="text.secondary">
                  {canPreview
                    ? "Click Preview to render the template"
                    : "Fill in subject, sender email and name to enable preview"}
                </Typography>
              </Stack>
            )
          )}
        </Box>
      )}

      {/* ---- Send Test Email Dialog ---- */}
      <Dialog open={sendTestOpen} onClose={() => setSendTestOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Send Test Email</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Send a test email using the current template and preview settings (
            {dataMode === "dummy"
              ? `dummy ${contactType} contact`
              : selectedContact
              ? `${selectedContact.firstName} ${selectedContact.lastName}`
              : "no contact selected"}
            ).
          </Typography>
          <TextField
            autoFocus
            label="Recipient Email"
            type="email"
            fullWidth
            value={recipientEmail}
            onChange={(e) => setRecipientEmail(e.target.value)}
            placeholder="Enter email address"
            sx={{ mt: 1 }}
          />
          {(!fromEmail || !fromName) && (
            <Alert severity="warning" sx={{ mt: 2 }}>
              Sender email and name are required in the template settings.
            </Alert>
          )}
          {!subject && (
            <Alert severity="warning" sx={{ mt: 1 }}>
              Template subject is required.
            </Alert>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSendTestOpen(false)} color="inherit">
            Cancel
          </Button>
          <Button
            onClick={handleSendTest}
            variant="contained"
            disabled={isSending || !recipientEmail.trim() || !fromEmail || !fromName || !subject}
            startIcon={
              isSending ? <CircularProgress size={16} color="inherit" /> : <Send size={16} />
            }
          >
            {isSending ? "Sending..." : "Send Test"}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};
