import { CoreModule, getCoreModuleRoute } from "../lib/router";
import {
  LayoutDashboard,
  FileText,
  MessageSquare,
  Image,
  Link,
  ShoppingCart,
  DollarSign,
  Users,
  Building2,
  Mail,
  BellOff,
  Globe,
  User,
  BookOpen,
  HelpCircle,
  Settings,
  ListChecks,
  Rocket,
  Megaphone,
} from "lucide-react";

export const MENU_CONFIG = [
  {
    header: "MAIN",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        icon: <LayoutDashboard size={20} />,
        entity: null,
        route: getCoreModuleRoute(CoreModule.dashboard),
      },
    ],
  },
  {
    header: "CMS",
    items: [
      {
        id: "content",
        label: "Content",
        icon: <FileText size={20} />,
        entity: "content",
        route: getCoreModuleRoute(CoreModule.content),
      },
      {
        id: "comments",
        label: "Comments",
        icon: <MessageSquare size={20} />,
        entity: "comment",
        route: getCoreModuleRoute(CoreModule.comments),
      },
      {
        id: "media",
        label: "Media",
        icon: <Image size={20} />,
        entity: "media",
        route: getCoreModuleRoute(CoreModule.media),
      },
      {
        id: "links",
        label: "Links",
        icon: <Link size={20} />,
        entity: "link",
        route: getCoreModuleRoute(CoreModule.links),
      },
    ],
  },
  {
    header: "CRM",
    items: [
      {
        id: "orders",
        label: "Orders",
        icon: <ShoppingCart size={20} />,
        entity: "order",
        route: getCoreModuleRoute(CoreModule.orders),
      },
      {
        id: "deals",
        label: "Deals",
        icon: <DollarSign size={20} />,
        entity: "deal",
        route: getCoreModuleRoute(CoreModule.deals),
      },
      {
        id: "contacts",
        label: "Contacts",
        icon: <Users size={20} />,
        entity: "contact",
        route: getCoreModuleRoute(CoreModule.contacts),
      },
      {
        id: "accounts",
        label: "Accounts",
        icon: <Building2 size={20} />,
        entity: "account",
        route: getCoreModuleRoute(CoreModule.accounts),
      },
    ],
  },
  {
    header: "MARKETING",
    items: [
      {
        id: "segments",
        label: "Segments",
        icon: <Users size={20} />,
        entity: "segment",
        route: getCoreModuleRoute(CoreModule.segments),
      },
      {
        id: "campaigns",
        label: "Campaigns",
        icon: <Megaphone size={20} />,
        entity: "campaign",
        route: getCoreModuleRoute(CoreModule.campaigns),
      },
      {
        id: "emailTemplates",
        label: "Email templates",
        icon: <Mail size={20} />,
        entity: "emailtemplate",
        route: getCoreModuleRoute(CoreModule.emailTemplates),
      },
      {
        id: "unsubscribes",
        label: "Unsubscribes",
        icon: <BellOff size={20} />,
        entity: "unsubscribe",
        route: getCoreModuleRoute(CoreModule.unsubscribes),
      },
      {
        id: "domains",
        label: "Domains",
        icon: <Globe size={20} />,
        entity: "domain",
        route: getCoreModuleRoute(CoreModule.domains),
      },
    ],
  },
  {
    header: "OPERATIONS",
    items: [
      {
        id: "deployments",
        label: "Deployments",
        icon: <Rocket size={20} />,
        entity: null,
        capability: "Deployment",
        route: getCoreModuleRoute(CoreModule.deployments),
      },
      {
        id: "tasks",
        label: "Tasks",
        icon: <ListChecks size={20} />,
        entity: null,
        route: getCoreModuleRoute(CoreModule.tasks),
      },
    ],
  },
  {
    header: "GENERAL",
    items: [
      {
        id: "settings",
        label: "Settings",
        icon: <Settings size={20} />,
        entity: null,
        route: getCoreModuleRoute(CoreModule.settings),
      },
      {
        id: "users",
        label: "Users",
        icon: <User size={20} />,
        entity: "user",
        route: getCoreModuleRoute(CoreModule.users),
      },
      {
        id: "activityLogs",
        label: "Activity logs",
        icon: <BookOpen size={20} />,
        entity: "activity-log",
        route: getCoreModuleRoute(CoreModule.activityLogs),
      },
      {
        id: "about",
        label: "About",
        icon: <HelpCircle size={20} />,
        entity: null,
        route: getCoreModuleRoute(CoreModule.about),
      },
    ],
  },
];
