import type { ContactDetailsDto } from "@lib/network/swagger-client";

/* ------------------------------------------------------------------ */
/*  Shared types                                                      */
/* ------------------------------------------------------------------ */

export type ContactType = "Full" | "Standard" | "Basic" | "Minimal";
export type PreviewDataMode = "dummy" | "contact";

export interface CustomParam {
  key: string;
  value: string;
  autoGenerated?: boolean;
}

export const CONTACT_TYPE_OPTIONS: {
  value: ContactType;
  label: string;
  description: string;
}[] = [
  { value: "Full", label: "Full", description: "All fields" },
  { value: "Standard", label: "Standard", description: "Common fields" },
  { value: "Basic", label: "Basic", description: "Minimal fields" },
  { value: "Minimal", label: "Minimal", description: "Essential only" },
];

/* ------------------------------------------------------------------ */
/*  Server-known contact parameters                                   */
/* ------------------------------------------------------------------ */

/**
 * Parameters the backend resolves from the contact record.
 * Any template token NOT in this set is considered a custom parameter.
 */
export const SERVER_KNOWN_PARAMS = new Set([
  "Email",
  "FirstName",
  "LastName",
  "FullName",
  "MiddleName",
  "Prefix",
  "Phone",
  "JobTitle",
  "CompanyName",
  "Department",
  "CityName",
  "State",
  "Zip",
  "Address1",
  "Address2",
  "Language",
  "CountryCode",
  "ContinentCode",
  "AccountName",
  "AccountSiteUrl",
  "DomainName",
]);

/** Case-insensitive lookup for server-known params. */
export const SERVER_KNOWN_LOWER = new Set([...SERVER_KNOWN_PARAMS].map((p) => p.toLowerCase()));

/* ------------------------------------------------------------------ */
/*  Template token extraction                                         */
/* ------------------------------------------------------------------ */

const LIQUID_CONTROL_KEYWORDS = new Set([
  "if",
  "else",
  "elsif",
  "endif",
  "unless",
  "endunless",
  "for",
  "endfor",
  "case",
  "endcase",
  "when",
  "capture",
  "endcapture",
  "comment",
  "endcomment",
  "raw",
  "endraw",
  "assign",
  "increment",
  "decrement",
  "include",
  "render",
  "break",
  "continue",
  "cycle",
  "tablerow",
  "endtablerow",
]);

/**
 * Extract simple (non-nested) Liquid-style tokens from template source.
 * Skips tokens containing dots (e.g. `account.name`) and Liquid
 * control tags like `if`, `endif`, `for`, `endfor`, `else`, etc.
 */
export function extractTemplateTokens(template: string): string[] {
  const seen = new Set<string>();
  const results: string[] = [];
  const re = /\{\{[-]?\s*([\w.]+)\s*[-]?\}\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(template)) !== null) {
    const token = m[1];
    if (token.includes(".")) continue;
    if (LIQUID_CONTROL_KEYWORDS.has(token.toLowerCase())) continue;
    if (!seen.has(token.toLowerCase())) {
      seen.add(token.toLowerCase());
      results.push(token);
    }
  }
  return results;
}

/* ------------------------------------------------------------------ */
/*  Sample value guesser                                              */
/* ------------------------------------------------------------------ */

/**
 * Best-guess a sample value for a custom template parameter
 * based on its name.
 */
export function guessParamValue(name: string): string {
  const lower = name.toLowerCase();

  if (lower.includes("email")) return "customer@example.com";
  if (lower.includes("name") && lower.includes("customer")) return "Alex Johnson";
  if (lower.includes("name")) return "Sample Name";
  if (lower.includes("phone") || lower.includes("tel")) return "+1-555-0100";
  if (lower.includes("date")) return "2026-01-15";
  if (lower.includes("url") || lower.includes("link")) return "https://example.com";
  if (lower.includes("amount") || lower.includes("total")) return "99.00";
  if (lower.includes("price") || lower.includes("fee")) return "19.99";
  if (lower.includes("currency")) return "USD";
  if (lower.includes("quantity") || lower.includes("qty")) return "1";
  if (lower.includes("id") || lower.includes("number")) return "12345";
  if (lower.includes("ref")) return "REF-001";
  if (lower.includes("code") || lower.includes("key")) return "XXXX-XXXX-XXXX";
  if (lower.includes("product")) return "Sample Product";
  if (lower.includes("source") || lower.includes("platform")) return "Web";
  if (lower.includes("order")) return "ORD-001";
  if (lower.includes("status")) return "Active";
  if (lower.includes("company") || lower.includes("org")) return "Acme Inc.";
  if (lower.includes("address")) return "123 Main Street";
  if (lower.includes("city")) return "New York";
  if (lower.includes("state")) return "NY";
  if (lower.includes("zip") || lower.includes("postal")) return "10001";
  if (lower.includes("country")) return "US";
  if (lower.includes("title")) return "Sample Title";
  if (lower.includes("description") || lower.includes("desc")) return "Sample description text";
  if (lower.includes("message") || lower.includes("note")) return "Sample message";
  if (lower.includes("license")) return "LIC-XXXX-XXXX";

  return `Sample ${name}`;
}

/* ------------------------------------------------------------------ */
/*  Local-storage helpers                                             */
/* ------------------------------------------------------------------ */

export function loadStored<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
}

export function saveStored(key: string, value: unknown): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* quota exceeded */
  }
}

/* ------------------------------------------------------------------ */
/*  Contact label                                                     */
/* ------------------------------------------------------------------ */

export function getContactLabel(c: ContactDetailsDto): string {
  const parts: string[] = [];
  if (c.firstName) parts.push(c.firstName);
  if (c.lastName) parts.push(c.lastName);
  const name = parts.join(" ") || "Unnamed";
  return c.email ? `${name} (${c.email})` : name;
}
